dataset_name: omega
# root_path: /zhome/8c/5/143289/GraPE/env/
root_path: /home/paul/Documents/spaghetti/GraPE/env/
file_name: "{{ root_path }}omega_splits.xlsx"
file_type: excel
smiles_column: Smiles
target_columns: ['Omega (-)']
global_features_column: null
split_column: Split
split_ratios: [0.8, 0.1, 0.1]  # used if split_column is not provided
model_save_path: "{{ root_path }}omega_model.pth"

fragmentation:
  scheme: "{{ root_path }}MG_plus_reference"  # Don't add .csv suffix!
  frag_save_file_path: "{{ root_path }}fragmentation_data_omega.pth"
  transfer_learning_frag_save_file_path: "{{ root_path }}tl_fragmentation_data_omega.pth"
  verbose: False

transfer_learning_dataset:
  training_data:
    file_name: "{{ root_path }}icas_omega.xlsx"
    file_type: excel
    smiles_column: SMILES
    target_columns: ['Omega (-)']
    global_features_columns: null
    split_column: null
    sheet_name: null
    split_ratios: [0.98, 0.01, 0.01]  # Optional, if no split column is provided
  validation_test_data: #for if val is taken from the real data instead of synthetic
    file_name: "{{ root_path }}omega_splits.xlsx"
    file_type: excel
    smiles_column: Smiles
    target_columns: ['Omega (-)']
    global_features_columns: null
    split_column: Split
    sheet_name: null
    split_ratios: [0.8, 0.1, 0.1]  # Optional, if no split column is provided
  model_save_path: "{{ root_path }}transfer_learning_omega_model.pth"