site_name: DGL Chem
site_author: aerte
docs_dir: source

theme:
    language: en
    name: material
    features:
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - mkdocstrings


nav:
  - Home: index.md
  - Code: api.md